# Write a program that manages a list of countries and their capital cities. It should
# prompt the user to enter the name of a country. If the program already "knows"
# the name of the capital city, it should display it. Otherwise it should ask the user to
# enter it. This should carry on until the user terminates the program (how this
# happens is up to you).
# Note: A good solution to this task will be able to cope with the country being entered
# variously as, for example, "Wales", "wales", "WALES" and so on.


countries_capitals = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Algeria": "Alger",
    "American Samoa": "Fagatogo",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Anguilla": "The Valley",
    "Antigua and Barbuda": "Saint John's",
    "Argentina": "Buenos Aires",
    "Armenia": "Yerevan",
    "Aruba": "Oranjestad",
    "Australia": "Canberra",
    "Austria": "Wien",
    "Azerbaijan": "Baku",
    "Bahamas": "Nassau",
    "Bahrain": "al-Manama",
    "Bangladesh": "Dhaka",
    "Barbados": "Bridgetown",
    "Belarus": "Minsk",
    "Belgium": "Bruxelles [Brussel]",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bermuda": "Hamilton",
    "Bhutan": "Thimphu",
    "Bolivia": "La Paz",
    "Bosnia and Herzegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Bouvet Island": None,
    "Brazil": "Brasília",
    "British Indian Ocean Territory": None,
    "Brunei": "Bandar Seri Begawan",
    "Bulgaria": "Sofia",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Bujumbura",
    "Cambodia": "Phnom Penh",
    "Cameroon": "Yaounde",
    "Canada": "Ottawa",
    "Cape Verde": "Praia",
    "Cayman Islands": "George Town",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Chile": "Santiago de Chile",
    "China": "Peking",
    "Christmas Island": "Flying Fish Cove",
    "Cocos (Keeling) Islands": "West Island",
    "Colombia": "Bogota",
    "Comoros": "Moroni",
    "Congo": "Brazzaville",
    "Cook Islands": "Avarua",
    "Costa Rica": "San José",
    "Croatia": "Zagreb",
    "Cuba": "La Habana",
    "Cyprus": "Nicosia",
    "Czech Republic": "Praha",
    "Denmark": "Copenhagen",
    "Djibouti": "Djibouti",
    "Dominica": "Roseau",
    "Dominican Republic": "Santo Domingo de Guzm",
    "East Timor": "Dili",
    "Ecuador": "Quito",
    "Egypt": "Cairo",
    "El Salvador": "San Salvador",
    "England": "London",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Estonia": "Tallinn",
    "Eswatini": "Mbabane",
    "Ethiopia": "Addis Abeba",
    "Falkland Islands": "Stanley",
    "Faroe Islands": "Tórshavn",
    "Fiji Islands": "Suva",
    "Finland": "Helsinki [Helsingfors]",
    "France": "Paris",
    "French Guiana": "Cayenne",
    "French Polynesia": "Papeete",
    "French Southern territories": None,
    "Gabon": "Libreville",
    "Gambia": "Banjul",
    "Georgia": "Tbilisi",
    "Germany": "Berlin",
    "Ghana": "Accra",
    "Gibraltar": "Gibraltar",
    "Greece": "Athenai",
    "Greenland": "Nuuk",
    "Grenada": "Saint George's",
    "Guadeloupe": "Basse-Terre",
    "Guam": "Aga",
    "Guatemala": "Ciudad de Guatemala",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Heard Island and McDonald Islands": None,
    "Holy See (Vatican City State)": "Citt",
    "Honduras": "Tegucigalpa",
    "Hong Kong": "Victoria",
    "Hungary": "Budapest",
    "Iceland": "Reykjavík",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Israel": "Jerusalem",
    "Italy": "Roma",
    "Ivory Coast": "Yamoussoukro",
    "Jamaica": "Kingston",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kenya": "Nairobi",
    "Kiribati": "Bairiki",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Latvia": "Riga",
    "Lebanon": "Beirut",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Liechtenstein": "Vaduz",
    "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg [Luxemburg/L",
    "Macao": "Macao",
    "North Macedonia": "Skopje",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malaysia": "Kuala Lumpur",
    "Maldives": "Male",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshall Islands": "Dalap-Uliga-Darrit",
    "Martinique": "Fort-de-France",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port-Louis",
    "Mayotte": "Mamoutzou",
    "Mexico": "Ciudad de M",
    "Micronesia: Federated States of": "Palikir",
    "Moldova": "Chisinau",
    "Monaco": "Monaco-Ville",
    "Mongolia": "Ulan Bator",
    "Montenegro": "Podgorica",
    "Montserrat": "Plymouth",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Myanmar": "Rangoon (Yangon)",
    "Namibia": "Windhoek",
    "Nauru": "Yaren",
    "Nepal": "Kathmandu",
    "Netherlands": "Amsterdam",
    "Netherlands Antilles": "Willemstad",
    "New Caledonia": "Noum",
    "New Zealand": "Wellington",
    "Nicaragua": "Managua",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Niue": "Alofi",
    "Norfolk Island": "Kingston",
    "North Korea": "Pyongyang",
    "Northern Ireland": "Belfast",
    "Northern Mariana Islands": "Garapan",
    "Norway": "Oslo",
    "Oman": "Masqat",
    "Pakistan": "Islamabad",
    "Palau": "Koror",
    "Palestine": "Gaza",
    "Panama": "Ciudad de Panamá",
    "Papua New Guinea": "Port Moresby",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Pitcairn": "Adamstown",
    "Poland": "Warszawa",
    "Portugal": "Lisboa",
    "Puerto Rico": "San Juan",
    "Qatar": "Doha",
    "Reunion": "Saint-Denis",
    "Romania": "Bucuresti",
    "Russia": "Moscow",
    "Rwanda": "Kigali",
    "Saint Helena": "Jamestown",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Pierre and Miquelon": "Saint-Pierre",
    "Saint Vincent and the Grenadines": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "São Tomé",
    "Saudi Arabia": "Riyadh",
    "Scotland": "Edinburgh",
    "Senegal": "Dakar",
    "Serbia": "Belgrade",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapore": "Singapore",
    "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana",
    "Solomon Islands": "Honiara",
    "Somalia": "Mogadishu",
    "South Africa": "Pretoria",
    "South Georgia and the South Sandwich Islands": None,
    "South Korea": "Seoul",
    "South Sudan": "Juba",
    "Spain": "Madrid",
    "Sri Lanka": "Colombo: Sri Jayawardenepura Kotte",
    "Sudan": "Khartum",
    "Suriname": "Paramaribo",
    "Svalbard and Jan Mayen": "Longyearbyen",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Syria": "Damascus",
    "Tajikistan": "Dushanbe",
    "Tanzania": "Dodoma",
    "Thailand": "Bangkok",
    "The Democratic Republic of Congo": "Kinshasa",
    "Togo": "Lomé",
    "Tokelau": "Fakaofo",
    "Tonga": "Nuku'alofa",
    "Trinidad and Tobago": "Port-of-Spain",
    "Tunisia": "Tunis",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "Turks and Caicos Islands": "Cockburn Town",
    "Tuvalu": "Funafuti",
    "Uganda": "Kampala",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington",
    "United States Minor Outlying Islands": None,
    "Uruguay": "Montevideo",
    "Uzbekistan": "Toskent",
    "Vanuatu": "Port-Vila",
    "Venezuela": "Caracas",
    "Vetican City": "Vetican City",
    "Vietnam": "Hanoi",
    "Virgin Islands: British": "Road Town",
    "Virgin Islands: U.S.": "Charlotte Amalie",
    "Wales": "Cardiff",
    "Wallis and Futuna": "Mata-Utu",
    "Western Sahara": "El-Aai",
    "Yemen": "Sanaa",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare"
}

def addCountry(countryName, capital):
    if countryName not in countries_capitals.keys() and capital not in countries_capitals.values():
        countries_capitals[countryName] = capital
        return True
    else:
        return False


def searchCapital(countryName):
    # Capitalize the country Name
    country = countryName.title()
    # Iterate over keys to find possible match
    for keys in countries_capitals.keys():
        # If country keys does not matches input country name, then return every possible value
        if country == keys:
            print(f"The capital of {keys} : {countries_capitals[keys]}")
        # If input country name matches any keyword of countryname keys, return the Capital city.
        elif country in keys:
            print(f"The capital of {keys} : {countries_capitals[keys]}")
    print("\nThe country that matches your queries are above.")
    consent = input("Enter y/n to confirm that you got the capital name of the country :")
    if consent.capitalize() == "N":
        countryName = input(f"Enter the Country Name :").title()
        capital = input(f"Enter the Capital of {countryName} :").title()
        if addCountry(countryName, capital):
            print("The country Has been Added Successfully.")
        else:
            print("Either the country already exist or the Capital.")



while True:
    countryName = input("Enter the Country Name :")
    searchCapital(countryName)
    consent = input("Do you want to continue for Another Search  y/n :")
    if consent.capitalize() == "N":
        break